name: Push branch
on:
  push:
jobs:
  Modules:
    name: Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
  ESLint:
    name: ESLint
    needs: Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Lint
        run: yarn lint
  Test:
    name: Test
    needs: Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Test
        run: yarn test
  Build:
    name: Build
    needs: Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Build
        run: yarn build

